source 'https://rubygems.org'

gem 'jekyll'
gem 'asciidoctor'
gem 'jekyll-asciidoc', :git => 'git@github.com:asciidoctor/jekyll-asciidoc.git'
gem 'tilt'
gem 'haml'
gem 'slim'
gem 'thread_safe'
gem 'asciidoctor-diagram'
gem 'coderay'
gem 'pygments.rb'
gem 'jekyll-paginate'
gem 'redcarpet'
gem 'jekyll-twitter-plugin'
gem 'jekyll-email-protect'
gem 'asciidoctor-pdf','>=1.5.0.alpha.11'
