source 'https://rubygems.org'

gem 'jekyll'
gem 'asciidoctor'
#gem 'jekyll-asciidoc', :git => 'https://github.com/asciidoctor/jekyll-asciidoc.git'
gem 'jekyll-asciidoc'
gem 'tilt'
gem 'haml'
gem 'slim'
gem 'thread_safe'
gem 'asciidoctor-diagram', '~> 1.2.0.pre'
gem 'coderay'
gem 'pygments.rb'
gem 'jekyll-paginate'
gem 'redcarpet'
gem 'jekyll-twitter-plugin'
gem 'jekyll-email-protect'
gem 'asciidoctor-pdf','>=1.5.0.alpha.11'
gem 'jekyll-mentions'
gem 'jemoji'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
