#!/bin/bash -e

user=jenkins
uid=$(id -u jenkins)
gid=$(id -g jenkins)
imgname=mhaberler/jekyll-asciidoctor
tag=${user}_${uid}_${gid}

cat Dockerfile.in >Dockerfile

cat >>Dockerfile <<EOF
# autogenerated by $0 on $(hostname)
RUN groupadd --gid $gid jenkins
RUN adduser --disabled-password --uid $uid --gid $gid --gecos "$user user" $user
ENV HOME  /home/$user
WORKDIR /home/$user
USER $user
EOF

echo building Docker image  $imgname:$tag

docker build -t $imgname:$tag .
