source 'https://rubygems.org'

# this may load higher minor versions like 3.1.4
gem 'jekyll', '~> 3.1.3'

gem 'asciidoctor', '~> 1.5.4'
#gem 'jekyll-asciidoc', :git => 'https://github.com/asciidoctor/jekyll-asciidoc.git'
gem 'jekyll-asciidoc', '~> 1.0.1'
gem 'tilt'
gem 'haml'
gem 'slim'
gem 'thread_safe'
gem 'asciidoctor-diagram', '~> 1.4.0'
gem 'coderay'
gem 'pygments.rb'
gem 'jekyll-paginate'
gem 'redcarpet'
gem 'jekyll-twitter-plugin'
gem 'jekyll-email-protect'
# gem 'asciidoctor-pdf' ,'>=1.5.0.alpha.11'
gem 'jekyll-mentions'
gem 'jemoji'
#gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-watch'
gem 'html-proofer'

# https://github.com/dommmel/jekyll-youtube
gem 'jekyll-youtube'

# https://github.com/mnuessler/jekyll-asciinema
gem 'jekyll-asciinema'

#https://github.com/bwillis/jekyll-github-sample
#gem 'jekyll_github_sample'

# nice: https://github.com/eug/jekyll-video-embed
# unsure how to install in container

#https://github.com/toshimaru/jekyll-toc
gem 'jekyll-toc'
