source 'https://rubygems.org'

gem 'jekyll', '~> 3.1.3'
gem 'asciidoctor', '~> 1.5.4'
#gem 'jekyll-asciidoc', :git => 'https://github.com/asciidoctor/jekyll-asciidoc.git'
gem 'jekyll-asciidoc', '~> 1.0.1'
gem 'tilt'
gem 'haml'
gem 'slim'
gem 'thread_safe'
gem 'asciidoctor-diagram', '~> 1.4.0'
gem 'coderay'
gem 'pygments.rb'
gem 'jekyll-paginate'
gem 'redcarpet'
gem 'jekyll-twitter-plugin'
gem 'jekyll-email-protect'
# gem 'asciidoctor-pdf' ,'>=1.5.0.alpha.11'
gem 'jekyll-mentions'
gem 'jemoji'
#gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-watch'
gem 'html-proofer'

