#!/bin/bash -e

username=$1
uid=$(id -u $username)
gid=$(id -g $username)
imgname=mhaberler/jekyll-asciidoctor
tag=${username}_${uid}_${gid}

cat >Dockerfile <<EOF
# autogenerated by $0 on $(hostname)

FROM haberlerm/docker-jekyll-asciidoctor

RUN groupadd --gid $gid $username
RUN adduser --disabled-password --uid $uid --gid $gid --gecos "$username user" $username
ENV HOME  /home/$username
USER $username

EOF



echo now run: docker build -t $imgname:$tag .
