#!/bin/bash -e

username=mah
uid=$(id -u $username)
gid=$(id -g $username)
imgname=machinekit/jekyll-asciidoctor
tag=${username}_${uid}_${gid}

cat >Dockerfile <<EOF
# autogenerated by $0 on $(hostname)

FROM machinekit/jekyll-asciidoctor-base

RUN groupadd --gid $gid $username
RUN adduser --disabled-password --uid $uid --gid $gid --gecos "$username user" $username
ENV HOME  /home/$username
USER $username

EOF

echo building Docker image  $imgname:$tag

docker build -t $imgname:$tag .
